use oak_core::{ElementType, Parser, UniversalElementRole};
#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[repr(u8)]
pub enum VocElementType {
    Root,
    SourceFile,
    Tag,
    Attribute,
    Interpolation,
    TemplateControl,

    // 基础
    Identifier,
    Keyword,
    StringLiteral,
    CharLiteral,
    IntegerLiteral,
    FloatLiteral,
    BoolLiteral,
    Number,

    // 关键字
    BoolKw,
    I8Kw,
    I16Kw,
    I32Kw,
    I64Kw,
    U8Kw,
    U16Kw,
    U32Kw,
    U64Kw,
    IntKw,
    UintKw,
    F32Kw,
    F64Kw,
    StringKw,
    CharKw,

    // 符号
    TagOpen,
    TagClose,
    TagSelfClose,
    TagSlash,
    AttrEq,

    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Ampersand,
    Pipe,
    Caret,
    Bang,
    Eq,
    LessThan,
    GreaterThan,
    Dot,
    Comma,
    Colon,
    Semicolon,
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    LeftBrace,
    RightBrace,
    Question,
    Tilde,

    // 复合符号
    PlusEq,
    MinusEq,
    StarEq,
    SlashEq,
    PercentEq,
    AmpersandEq,
    PipeEq,
    CaretEq,
    EqEq,
    Ne,
    Le,
    Ge,
    PlusPlus,
    MinusMinus,
    AndAnd,
    OrOr,
    LeftShift,
    LeftShiftEq,
    RightShift,
    RightShiftEq,
    DotDot,
    DotDotDot,
    Arrow,
    FatArrow,

    // 模板
    InterpolationStart,
    InterpolationEnd,
    TemplateControlStart,
    TemplateControlEnd,
    TextPart,

    // 杂项
    Whitespace,
    Newline,
    Comment,
    Error,
    Eof,
}

impl ElementType for VocElementType {
    type Role = UniversalElementRole;

    fn role(&self) -> Self::Role {
        match self {
            Self::Root => UniversalElementRole::Root,

            Self::Error => UniversalElementRole::Error,
            _ => UniversalElementRole::None,
        }
    }
}

impl From<crate::lexer::token_type::VocTokenType> for VocElementType {
    fn from(token: crate::lexer::token_type::VocTokenType) -> Self {
        use crate::lexer::token_type::VocTokenType;
        match token {
            VocTokenType::Root => Self::Root,
            VocTokenType::Identifier => Self::Identifier,
            VocTokenType::Keyword(_) => Self::Keyword,
            VocTokenType::StringLiteral => Self::StringLiteral,
            VocTokenType::CharLiteral => Self::CharLiteral,
            VocTokenType::IntegerLiteral => Self::IntegerLiteral,
            VocTokenType::FloatLiteral => Self::FloatLiteral,
            VocTokenType::BoolLiteral => Self::BoolLiteral,
            VocTokenType::Number => Self::Number,
            VocTokenType::BoolKw => Self::BoolKw,
            VocTokenType::I8Kw => Self::I8Kw,
            VocTokenType::I16Kw => Self::I16Kw,
            VocTokenType::I32Kw => Self::I32Kw,
            VocTokenType::I64Kw => Self::I64Kw,
            VocTokenType::U8Kw => Self::U8Kw,
            VocTokenType::U16Kw => Self::U16Kw,
            VocTokenType::U32Kw => Self::U32Kw,
            VocTokenType::U64Kw => Self::U64Kw,
            VocTokenType::IntKw => Self::IntKw,
            VocTokenType::UintKw => Self::UintKw,
            VocTokenType::F32Kw => Self::F32Kw,
            VocTokenType::F64Kw => Self::F64Kw,
            VocTokenType::StringKw => Self::StringKw,
            VocTokenType::CharKw => Self::CharKw,
            VocTokenType::TagOpen => Self::TagOpen,
            VocTokenType::TagClose => Self::TagClose,
            VocTokenType::TagSelfClose => Self::TagSelfClose,
            VocTokenType::TagSlash => Self::TagSlash,
            VocTokenType::AttrEq => Self::AttrEq,
            VocTokenType::Plus => Self::Plus,
            VocTokenType::Minus => Self::Minus,
            VocTokenType::Star => Self::Star,
            VocTokenType::Slash => Self::Slash,
            VocTokenType::Percent => Self::Percent,
            VocTokenType::Ampersand => Self::Ampersand,
            VocTokenType::Pipe => Self::Pipe,
            VocTokenType::Caret => Self::Caret,
            VocTokenType::Bang => Self::Bang,
            VocTokenType::Eq => Self::Eq,
            VocTokenType::LessThan => Self::LessThan,
            VocTokenType::GreaterThan => Self::GreaterThan,
            VocTokenType::Dot => Self::Dot,
            VocTokenType::Comma => Self::Comma,
            VocTokenType::Colon => Self::Colon,
            VocTokenType::Semicolon => Self::Semicolon,
            VocTokenType::LeftParen => Self::LeftParen,
            VocTokenType::RightParen => Self::RightParen,
            VocTokenType::LeftBracket => Self::LeftBracket,
            VocTokenType::RightBracket => Self::RightBracket,
            VocTokenType::LeftBrace => Self::LeftBrace,
            VocTokenType::RightBrace => Self::RightBrace,
            VocTokenType::Question => Self::Question,
            VocTokenType::Tilde => Self::Tilde,
            VocTokenType::PlusEq => Self::PlusEq,
            VocTokenType::MinusEq => Self::MinusEq,
            VocTokenType::StarEq => Self::StarEq,
            VocTokenType::SlashEq => Self::SlashEq,
            VocTokenType::PercentEq => Self::PercentEq,
            VocTokenType::AmpersandEq => Self::AmpersandEq,
            VocTokenType::PipeEq => Self::PipeEq,
            VocTokenType::CaretEq => Self::CaretEq,
            VocTokenType::EqEq => Self::EqEq,
            VocTokenType::Ne => Self::Ne,
            VocTokenType::Le => Self::Le,
            VocTokenType::Ge => Self::Ge,
            VocTokenType::PlusPlus => Self::PlusPlus,
            VocTokenType::MinusMinus => Self::MinusMinus,
            VocTokenType::AndAnd => Self::AndAnd,
            VocTokenType::OrOr => Self::OrOr,
            VocTokenType::LeftShift => Self::LeftShift,
            VocTokenType::LeftShiftEq => Self::LeftShiftEq,
            VocTokenType::RightShift => Self::RightShift,
            VocTokenType::RightShiftEq => Self::RightShiftEq,
            VocTokenType::DotDot => Self::DotDot,
            VocTokenType::DotDotDot => Self::DotDotDot,
            VocTokenType::Arrow => Self::Arrow,
            VocTokenType::FatArrow => Self::FatArrow,
            VocTokenType::InterpolationStart => Self::InterpolationStart,
            VocTokenType::InterpolationEnd => Self::InterpolationEnd,
            VocTokenType::TemplateControlStart => Self::TemplateControlStart,
            VocTokenType::TemplateControlEnd => Self::TemplateControlEnd,
            VocTokenType::TextPart => Self::TextPart,
            VocTokenType::Whitespace => Self::Whitespace,
            VocTokenType::Newline => Self::Newline,
            VocTokenType::Comment => Self::Comment,
            VocTokenType::Error => Self::Error,
            VocTokenType::Eof => Self::Eof,
        }
    }
}
