use crate::lexer::token_type::WgslTokenType;
use oak_core::{ElementType, UniversalElementRole};
#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub enum WgslElementType {
    // Tokens (mapped from WgslTokenType)
    Whitespace,
    Newline,
    Comment,
    Error,
    Eof,
    Text,

    // Literals
    IntegerLiteral,
    FloatLiteral,
    StringLiteral,
    BoolLiteral,
    Identifier,

    // Keywords - Types
    BoolKw,
    I32Kw,
    U32Kw,
    F32Kw,
    F16Kw,
    Vec2Kw,
    Vec3Kw,
    Vec4Kw,
    Mat2x2Kw,
    Mat2x3Kw,
    Mat2x4Kw,
    Mat3x2Kw,
    Mat3x3Kw,
    Mat3x4Kw,
    Mat4x2Kw,
    Mat4x3Kw,
    Mat4x4Kw,
    ArrayKw,
    PtrKw,
    AtomicKw,
    SamplerKw,
    SamplerComparisonKw,
    Texture1dKw,
    Texture2dKw,
    Texture2dArrayKw,
    Texture3dKw,
    TextureCubeKw,
    TextureCubeArrayKw,
    TextureMultisampled2dKw,
    TextureDepth2dKw,
    TextureDepthCubeKw,
    TextureDepthMultisampled2dKw,
    TextureStorage1dKw,
    TextureStorage2dKw,
    TextureStorage2dArrayKw,
    TextureStorage3dKw,

    // Keywords - Control flow
    FnKw,
    VarKw,
    LetKw,
    ConstKw,
    IfKw,
    ElseKw,
    SwitchKw,
    CaseKw,
    DefaultKw,
    LoopKw,
    ForKw,
    WhileKw,
    BreakKw,
    ContinueKw,
    ReturnKw,
    DiscardKw,

    // Keywords - Storage
    FunctionKw,
    PrivateKw,
    WorkgroupKw,
    UniformKw,
    StorageKw,

    // Access modes
    ReadKw,
    WriteKw,
    ReadWriteKw,

    // Keywords - Shader stages & Attributes
    VertexKw,
    FragmentKw,
    ComputeKw,
    BindingKw,
    GroupKw,
    LocationKw,
    BuiltinKw,
    InterpolateKw,
    InvariantKw,
    SizeKw,
    AlignKw,
    WorkgroupSizeKw,

    // Keywords - Builtins
    PositionKw,
    VertexIndexKw,
    InstanceIndexKw,
    FrontFacingKw,
    FragDepthKw,
    LocalInvocationIdKw,
    LocalInvocationIndexKw,
    GlobalInvocationIdKw,
    WorkgroupIdKw,
    NumWorkgroupsKw,
    SampleIndexKw,
    SampleMaskKw,

    // Keywords - Others
    StructKw,
    TypeKw,
    AliasKw,
    EnableKw,
    RequiresKw,
    OverrideKw,

    // Operators
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Ampersand,
    Pipe,
    Caret,
    Tilde,
    LeftShift,
    RightShift,
    PlusAssign,
    MinusAssign,
    StarAssign,
    SlashAssign,
    PercentAssign,
    AmpersandAssign,
    PipeAssign,
    CaretAssign,
    LeftShiftAssign,
    RightShiftAssign,
    Increment,
    Decrement,

    // Comparison
    Eq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
    EqEq,
    BangEq,
    LtLt,
    GtGt,

    // Logical
    AmpersandAmpersand,
    PipePipe,
    Bang,

    // Assignment
    Assign,
    Arrow,

    // Punctuation
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Semicolon,
    Comma,
    Dot,
    Colon,
    Question,
    At,
    Hash,
    Dollar,

    // Grammar nodes
    Root,
    Function,
    Struct,
    Variable,
    Block,
    TypeAlias,
}

impl ElementType for WgslElementType {
    type Role = UniversalElementRole;

    fn role(&self) -> Self::Role {
        match self {
            _ => UniversalElementRole::None,
        }
    }
}

impl From<WgslTokenType> for WgslElementType {
    fn from(token: WgslTokenType) -> Self {
        match token {
            WgslTokenType::Whitespace => Self::Whitespace,
            WgslTokenType::Newline => Self::Newline,
            WgslTokenType::Comment => Self::Comment,
            WgslTokenType::Error => Self::Error,
            WgslTokenType::Eof => Self::Eof,
            WgslTokenType::Text => Self::Text,
            WgslTokenType::IntegerLiteral => Self::IntegerLiteral,
            WgslTokenType::FloatLiteral => Self::FloatLiteral,
            WgslTokenType::StringLiteral => Self::StringLiteral,
            WgslTokenType::BoolLiteral => Self::BoolLiteral,
            WgslTokenType::Identifier => Self::Identifier,
            WgslTokenType::BoolKw => Self::BoolKw,
            WgslTokenType::I32Kw => Self::I32Kw,
            WgslTokenType::U32Kw => Self::U32Kw,
            WgslTokenType::F32Kw => Self::F32Kw,
            WgslTokenType::F16Kw => Self::F16Kw,
            WgslTokenType::Vec2Kw => Self::Vec2Kw,
            WgslTokenType::Vec3Kw => Self::Vec3Kw,
            WgslTokenType::Vec4Kw => Self::Vec4Kw,
            WgslTokenType::Mat2x2Kw => Self::Mat2x2Kw,
            WgslTokenType::Mat2x3Kw => Self::Mat2x3Kw,
            WgslTokenType::Mat2x4Kw => Self::Mat2x4Kw,
            WgslTokenType::Mat3x2Kw => Self::Mat3x2Kw,
            WgslTokenType::Mat3x3Kw => Self::Mat3x3Kw,
            WgslTokenType::Mat3x4Kw => Self::Mat3x4Kw,
            WgslTokenType::Mat4x2Kw => Self::Mat4x2Kw,
            WgslTokenType::Mat4x3Kw => Self::Mat4x3Kw,
            WgslTokenType::Mat4x4Kw => Self::Mat4x4Kw,
            WgslTokenType::ArrayKw => Self::ArrayKw,
            WgslTokenType::PtrKw => Self::PtrKw,
            WgslTokenType::AtomicKw => Self::AtomicKw,
            WgslTokenType::SamplerKw => Self::SamplerKw,
            WgslTokenType::SamplerComparisonKw => Self::SamplerComparisonKw,
            WgslTokenType::Texture1dKw => Self::Texture1dKw,
            WgslTokenType::Texture2dKw => Self::Texture2dKw,
            WgslTokenType::Texture2dArrayKw => Self::Texture2dArrayKw,
            WgslTokenType::Texture3dKw => Self::Texture3dKw,
            WgslTokenType::TextureCubeKw => Self::TextureCubeKw,
            WgslTokenType::TextureCubeArrayKw => Self::TextureCubeArrayKw,
            WgslTokenType::TextureMultisampled2dKw => Self::TextureMultisampled2dKw,
            WgslTokenType::TextureDepth2dKw => Self::TextureDepth2dKw,
            WgslTokenType::TextureDepthCubeKw => Self::TextureDepthCubeKw,
            WgslTokenType::TextureDepthMultisampled2dKw => Self::TextureDepthMultisampled2dKw,
            WgslTokenType::TextureStorage1dKw => Self::TextureStorage1dKw,
            WgslTokenType::TextureStorage2dKw => Self::TextureStorage2dKw,
            WgslTokenType::TextureStorage2dArrayKw => Self::TextureStorage2dArrayKw,
            WgslTokenType::TextureStorage3dKw => Self::TextureStorage3dKw,
            WgslTokenType::FnKw => Self::FnKw,
            WgslTokenType::VarKw => Self::VarKw,
            WgslTokenType::LetKw => Self::LetKw,
            WgslTokenType::ConstKw => Self::ConstKw,
            WgslTokenType::IfKw => Self::IfKw,
            WgslTokenType::ElseKw => Self::ElseKw,
            WgslTokenType::SwitchKw => Self::SwitchKw,
            WgslTokenType::CaseKw => Self::CaseKw,
            WgslTokenType::DefaultKw => Self::DefaultKw,
            WgslTokenType::LoopKw => Self::LoopKw,
            WgslTokenType::ForKw => Self::ForKw,
            WgslTokenType::WhileKw => Self::WhileKw,
            WgslTokenType::BreakKw => Self::BreakKw,
            WgslTokenType::ContinueKw => Self::ContinueKw,
            WgslTokenType::ReturnKw => Self::ReturnKw,
            WgslTokenType::DiscardKw => Self::DiscardKw,
            WgslTokenType::FunctionKw => Self::FunctionKw,
            WgslTokenType::PrivateKw => Self::PrivateKw,
            WgslTokenType::WorkgroupKw => Self::WorkgroupKw,
            WgslTokenType::UniformKw => Self::UniformKw,
            WgslTokenType::StorageKw => Self::StorageKw,
            WgslTokenType::ReadKw => Self::ReadKw,
            WgslTokenType::WriteKw => Self::WriteKw,
            WgslTokenType::ReadWriteKw => Self::ReadWriteKw,
            WgslTokenType::VertexKw => Self::VertexKw,
            WgslTokenType::FragmentKw => Self::FragmentKw,
            WgslTokenType::ComputeKw => Self::ComputeKw,
            WgslTokenType::BindingKw => Self::BindingKw,
            WgslTokenType::GroupKw => Self::GroupKw,
            WgslTokenType::LocationKw => Self::LocationKw,
            WgslTokenType::BuiltinKw => Self::BuiltinKw,
            WgslTokenType::InterpolateKw => Self::InterpolateKw,
            WgslTokenType::InvariantKw => Self::InvariantKw,
            WgslTokenType::SizeKw => Self::SizeKw,
            WgslTokenType::AlignKw => Self::AlignKw,
            WgslTokenType::WorkgroupSizeKw => Self::WorkgroupSizeKw,
            WgslTokenType::PositionKw => Self::PositionKw,
            WgslTokenType::VertexIndexKw => Self::VertexIndexKw,
            WgslTokenType::InstanceIndexKw => Self::InstanceIndexKw,
            WgslTokenType::FrontFacingKw => Self::FrontFacingKw,
            WgslTokenType::FragDepthKw => Self::FragDepthKw,
            WgslTokenType::LocalInvocationIdKw => Self::LocalInvocationIdKw,
            WgslTokenType::LocalInvocationIndexKw => Self::LocalInvocationIndexKw,
            WgslTokenType::GlobalInvocationIdKw => Self::GlobalInvocationIdKw,
            WgslTokenType::WorkgroupIdKw => Self::WorkgroupIdKw,
            WgslTokenType::NumWorkgroupsKw => Self::NumWorkgroupsKw,
            WgslTokenType::SampleIndexKw => Self::SampleIndexKw,
            WgslTokenType::SampleMaskKw => Self::SampleMaskKw,
            WgslTokenType::StructKw => Self::StructKw,
            WgslTokenType::TypeKw => Self::TypeKw,
            WgslTokenType::AliasKw => Self::AliasKw,
            WgslTokenType::EnableKw => Self::EnableKw,
            WgslTokenType::RequiresKw => Self::RequiresKw,
            WgslTokenType::OverrideKw => Self::OverrideKw,
            WgslTokenType::Plus => Self::Plus,
            WgslTokenType::Minus => Self::Minus,
            WgslTokenType::Star => Self::Star,
            WgslTokenType::Slash => Self::Slash,
            WgslTokenType::Percent => Self::Percent,
            WgslTokenType::Ampersand => Self::Ampersand,
            WgslTokenType::Pipe => Self::Pipe,
            WgslTokenType::Caret => Self::Caret,
            WgslTokenType::Tilde => Self::Tilde,
            WgslTokenType::LeftShift => Self::LeftShift,
            WgslTokenType::RightShift => Self::RightShift,
            WgslTokenType::PlusAssign => Self::PlusAssign,
            WgslTokenType::MinusAssign => Self::MinusAssign,
            WgslTokenType::StarAssign => Self::StarAssign,
            WgslTokenType::SlashAssign => Self::SlashAssign,
            WgslTokenType::PercentAssign => Self::PercentAssign,
            WgslTokenType::AmpersandAssign => Self::AmpersandAssign,
            WgslTokenType::PipeAssign => Self::PipeAssign,
            WgslTokenType::CaretAssign => Self::CaretAssign,
            WgslTokenType::LeftShiftAssign => Self::LeftShiftAssign,
            WgslTokenType::RightShiftAssign => Self::RightShiftAssign,
            WgslTokenType::Increment => Self::Increment,
            WgslTokenType::Decrement => Self::Decrement,
            WgslTokenType::Eq => Self::Eq,
            WgslTokenType::Ne => Self::Ne,
            WgslTokenType::Lt => Self::Lt,
            WgslTokenType::Le => Self::Le,
            WgslTokenType::Gt => Self::Gt,
            WgslTokenType::Ge => Self::Ge,
            WgslTokenType::EqEq => Self::EqEq,
            WgslTokenType::BangEq => Self::BangEq,
            WgslTokenType::LtLt => Self::LtLt,
            WgslTokenType::GtGt => Self::GtGt,
            WgslTokenType::AmpersandAmpersand => Self::AmpersandAmpersand,
            WgslTokenType::PipePipe => Self::PipePipe,
            WgslTokenType::Bang => Self::Bang,
            WgslTokenType::Assign => Self::Assign,
            WgslTokenType::Arrow => Self::Arrow,
            WgslTokenType::LeftParen => Self::LeftParen,
            WgslTokenType::RightParen => Self::RightParen,
            WgslTokenType::LeftBrace => Self::LeftBrace,
            WgslTokenType::RightBrace => Self::RightBrace,
            WgslTokenType::LeftBracket => Self::LeftBracket,
            WgslTokenType::RightBracket => Self::RightBracket,
            WgslTokenType::Semicolon => Self::Semicolon,
            WgslTokenType::Comma => Self::Comma,
            WgslTokenType::Dot => Self::Dot,
            WgslTokenType::Colon => Self::Colon,
            WgslTokenType::Question => Self::Question,
            WgslTokenType::At => Self::At,
            WgslTokenType::Hash => Self::Hash,
            WgslTokenType::Dollar => Self::Dollar,
            WgslTokenType::Root => Self::Root,
            WgslTokenType::Function => Self::Function,
            WgslTokenType::Struct => Self::Struct,
            WgslTokenType::Variable => Self::Variable,
            WgslTokenType::Block => Self::Block,
            WgslTokenType::TypeAlias => Self::TypeAlias,
        }
    }
}
