use oak_core::{ElementType, UniversalElementRole};
#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub enum ZigElementType {
    Root,
    // 基础 kind
    Whitespace,
    Newline,
    Comment,
    DocComment,
    Error,
    Eof,

    // 字面量
    Identifier,
    StringLiteral,
    CharLiteral,
    IntegerLiteral,
    FloatLiteral,
    BooleanLiteral,
    Literal, // Added

    // Zig 关键字 - 基本结构
    Const,
    Var,
    Fn,
    Struct,
    Union,
    Enum,
    Opaque,
    Type,
    Comptime,
    Inline,
    NoInline,
    Pub,
    Export,
    Extern,
    Packed,
    Align,
    CallConv,
    LinkSection,

    // Zig 关键字 - 控制流
    If,
    Else,
    Switch,
    While,
    For,
    Break,
    Continue,
    Return,
    Defer,
    ErrDefer,
    Unreachable,
    NoReturn,

    // Zig 关键字 - 错误处理
    ErrorKeyword,

    // Zig 关键字 - 测试和异步
    Test,
    Async,
    Await,
    Suspend,
    Resume,
    Cancel,

    // Zig 关键字 - 内存管理
    Undefined,
    Null,
    Volatile,
    AllowZero,
    NoAlias,

    // Zig 关键字 - 其他
    And,
    Or,
    AnyFrame,
    AnyType,
    ThreadLocal,

    // 基本类型
    Bool,
    I8,
    I16,
    I32,
    I64,
    I128,
    Isize,
    U8,
    U16,
    U32,
    U64,
    U128,
    Usize,
    F16,
    F32,
    F64,
    F80,
    F128,
    CShort,
    CUshort,
    CInt,
    CUint,
    CLong,
    CUlong,
    CLongLong,
    CUlongLong,
    CLongDouble,
    CVoid,
    Void,
    ComptimeInt,
    ComptimeFloat,

    // 操作符
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    StarStar,
    PlusPercent,
    MinusPercent,
    StarPercent,
    PlusPlus,
    MinusMinus,

    // 位操作符
    Ampersand,
    Pipe,
    Caret,
    Tilde,
    LessLess,
    GreaterGreater,

    // 比较操作符
    Equal,
    NotEqual,
    Less,
    Greater,
    LessEqual,
    GreaterEqual,

    // 逻辑操作符
    AndAnd,
    OrOr,

    // 赋值操作符
    Assign,
    PlusAssign,
    MinusAssign,
    StarAssign,
    SlashAssign,
    PercentAssign,
    AmpersandAssign,
    PipeAssign,
    CaretAssign,
    LessLessAssign,
    GreaterGreaterAssign,

    // 标点符号
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Semicolon,
    Comma,
    Dot,
    DotDot,
    DotDotDot,
    DotQuestion,
    DotStar,
    Colon,
    Question,
    Exclamation,
    Arrow,
    FatArrow,
    OrElse,
    CatchKeyword,
    TryKeyword,
    AwaitKeyword,
    At,
    BuiltinIdentifier,
    StringStart,
    StringEnd,
    StringContent,
    InterpolationStart,
    InterpolationEnd,
    MultilineStringStart,
    MultilineStringEnd,
    MultilineStringContent,
    CompileDirective,
    Text,

    // 语法结构
    FnDeclaration,
    VarDeclaration,
    StructDeclaration,
    EnumDeclaration,
    UnionDeclaration,
    IfStatement,
    WhileStatement,
    ForStatement,
    ReturnStatement,
    Block,
    BinaryExpr,
    UnaryExpr,
}

impl ElementType for ZigElementType {
    type Role = UniversalElementRole;

    fn role(&self) -> Self::Role {
        match self {
            _ => UniversalElementRole::None,
        }
    }
}

impl From<crate::lexer::token_type::ZigTokenType> for ZigElementType {
    fn from(token: crate::lexer::token_type::ZigTokenType) -> Self {
        use crate::lexer::token_type::ZigTokenType as T;
        match token {
            T::Root => ZigElementType::Root,
            T::Whitespace => ZigElementType::Whitespace,
            T::Newline => ZigElementType::Newline,
            T::Comment => ZigElementType::Comment,
            T::DocComment => ZigElementType::DocComment,
            T::Error => ZigElementType::Error,
            T::Eof => ZigElementType::Eof,
            T::Identifier => ZigElementType::Identifier,
            T::StringLiteral => ZigElementType::StringLiteral,
            T::CharLiteral => ZigElementType::CharLiteral,
            T::IntegerLiteral => ZigElementType::IntegerLiteral,
            T::FloatLiteral => ZigElementType::FloatLiteral,
            T::BooleanLiteral => ZigElementType::BooleanLiteral,
            T::Const => ZigElementType::Const,
            T::Var => ZigElementType::Var,
            T::Fn => ZigElementType::Fn,
            T::Struct => ZigElementType::Struct,
            T::Union => ZigElementType::Union,
            T::Enum => ZigElementType::Enum,
            T::Opaque => ZigElementType::Opaque,
            T::Type => ZigElementType::Type,
            T::Comptime => ZigElementType::Comptime,
            T::Inline => ZigElementType::Inline,
            T::NoInline => ZigElementType::NoInline,
            T::Pub => ZigElementType::Pub,
            T::Export => ZigElementType::Export,
            T::Extern => ZigElementType::Extern,
            T::Packed => ZigElementType::Packed,
            T::Align => ZigElementType::Align,
            T::CallConv => ZigElementType::CallConv,
            T::LinkSection => ZigElementType::LinkSection,
            T::If => ZigElementType::If,
            T::Else => ZigElementType::Else,
            T::Switch => ZigElementType::Switch,
            T::While => ZigElementType::While,
            T::For => ZigElementType::For,
            T::Break => ZigElementType::Break,
            T::Continue => ZigElementType::Continue,
            T::Return => ZigElementType::Return,
            T::Defer => ZigElementType::Defer,
            T::ErrDefer => ZigElementType::ErrDefer,
            T::Unreachable => ZigElementType::Unreachable,
            T::NoReturn => ZigElementType::NoReturn,
            T::ErrorKeyword => ZigElementType::ErrorKeyword,
            T::Test => ZigElementType::Test,
            T::Async => ZigElementType::Async,
            T::Await => ZigElementType::Await,
            T::Suspend => ZigElementType::Suspend,
            T::Resume => ZigElementType::Resume,
            T::Cancel => ZigElementType::Cancel,
            T::Undefined => ZigElementType::Undefined,
            T::Null => ZigElementType::Null,
            T::Volatile => ZigElementType::Volatile,
            T::AllowZero => ZigElementType::AllowZero,
            T::NoAlias => ZigElementType::NoAlias,
            T::And => ZigElementType::And,
            T::Or => ZigElementType::Or,
            T::AnyFrame => ZigElementType::AnyFrame,
            T::AnyType => ZigElementType::AnyType,
            T::ThreadLocal => ZigElementType::ThreadLocal,
            T::Bool => ZigElementType::Bool,
            T::I8 => ZigElementType::I8,
            T::I16 => ZigElementType::I16,
            T::I32 => ZigElementType::I32,
            T::I64 => ZigElementType::I64,
            T::I128 => ZigElementType::I128,
            T::Isize => ZigElementType::Isize,
            T::U8 => ZigElementType::U8,
            T::U16 => ZigElementType::U16,
            T::U32 => ZigElementType::U32,
            T::U64 => ZigElementType::U64,
            T::U128 => ZigElementType::U128,
            T::Usize => ZigElementType::Usize,
            T::F16 => ZigElementType::F16,
            T::F32 => ZigElementType::F32,
            T::F64 => ZigElementType::F64,
            T::F80 => ZigElementType::F80,
            T::F128 => ZigElementType::F128,
            T::CShort => ZigElementType::CShort,
            T::CUshort => ZigElementType::CUshort,
            T::CInt => ZigElementType::CInt,
            T::CUint => ZigElementType::CUint,
            T::CLong => ZigElementType::CLong,
            T::CUlong => ZigElementType::CUlong,
            T::CLongLong => ZigElementType::CLongLong,
            T::CUlongLong => ZigElementType::CUlongLong,
            T::CLongDouble => ZigElementType::CLongDouble,
            T::CVoid => ZigElementType::CVoid,
            T::Void => ZigElementType::Void,
            T::ComptimeInt => ZigElementType::ComptimeInt,
            T::ComptimeFloat => ZigElementType::ComptimeFloat,
            T::Plus => ZigElementType::Plus,
            T::Minus => ZigElementType::Minus,
            T::Star => ZigElementType::Star,
            T::Slash => ZigElementType::Slash,
            T::Percent => ZigElementType::Percent,
            T::StarStar => ZigElementType::StarStar,
            T::PlusPercent => ZigElementType::PlusPercent,
            T::MinusPercent => ZigElementType::MinusPercent,
            T::StarPercent => ZigElementType::StarPercent,
            T::PlusPlus => ZigElementType::PlusPlus,
            T::MinusMinus => ZigElementType::MinusMinus,
            T::Ampersand => ZigElementType::Ampersand,
            T::Pipe => ZigElementType::Pipe,
            T::Caret => ZigElementType::Caret,
            T::Tilde => ZigElementType::Tilde,
            T::LessLess => ZigElementType::LessLess,
            T::GreaterGreater => ZigElementType::GreaterGreater,
            T::Equal => ZigElementType::Equal,
            T::NotEqual => ZigElementType::NotEqual,
            T::Less => ZigElementType::Less,
            T::Greater => ZigElementType::Greater,
            T::LessEqual => ZigElementType::LessEqual,
            T::GreaterEqual => ZigElementType::GreaterEqual,
            T::AndAnd => ZigElementType::AndAnd,
            T::OrOr => ZigElementType::OrOr,
            T::Assign => ZigElementType::Assign,
            T::PlusAssign => ZigElementType::PlusAssign,
            T::MinusAssign => ZigElementType::MinusAssign,
            T::StarAssign => ZigElementType::StarAssign,
            T::SlashAssign => ZigElementType::SlashAssign,
            T::PercentAssign => ZigElementType::PercentAssign,
            T::AmpersandAssign => ZigElementType::AmpersandAssign,
            T::PipeAssign => ZigElementType::PipeAssign,
            T::CaretAssign => ZigElementType::CaretAssign,
            T::LessLessAssign => ZigElementType::LessLessAssign,
            T::GreaterGreaterAssign => ZigElementType::GreaterGreaterAssign,
            T::LeftParen => ZigElementType::LeftParen,
            T::RightParen => ZigElementType::RightParen,
            T::LeftBrace => ZigElementType::LeftBrace,
            T::RightBrace => ZigElementType::RightBrace,
            T::LeftBracket => ZigElementType::LeftBracket,
            T::RightBracket => ZigElementType::RightBracket,
            T::Semicolon => ZigElementType::Semicolon,
            T::Comma => ZigElementType::Comma,
            T::Dot => ZigElementType::Dot,
            T::DotDot => ZigElementType::DotDot,
            T::DotDotDot => ZigElementType::DotDotDot,
            T::DotQuestion => ZigElementType::DotQuestion,
            T::DotStar => ZigElementType::DotStar,
            T::Colon => ZigElementType::Colon,
            T::Question => ZigElementType::Question,
            T::Exclamation => ZigElementType::Exclamation,
            T::Arrow => ZigElementType::Arrow,
            T::FatArrow => ZigElementType::FatArrow,
            T::OrElse => ZigElementType::OrElse,
            T::CatchKeyword => ZigElementType::CatchKeyword,
            T::TryKeyword => ZigElementType::TryKeyword,
            T::AwaitKeyword => ZigElementType::AwaitKeyword,
            T::At => ZigElementType::At,
            T::BuiltinIdentifier => ZigElementType::BuiltinIdentifier,
            T::StringStart => ZigElementType::StringStart,
            T::StringEnd => ZigElementType::StringEnd,
            T::StringContent => ZigElementType::StringContent,
            T::InterpolationStart => ZigElementType::InterpolationStart,
            T::InterpolationEnd => ZigElementType::InterpolationEnd,
            T::MultilineStringStart => ZigElementType::MultilineStringStart,
            T::MultilineStringEnd => ZigElementType::MultilineStringEnd,
            T::MultilineStringContent => ZigElementType::MultilineStringContent,
            T::CompileDirective => ZigElementType::CompileDirective,
            T::Text => ZigElementType::Text,
            T::FnDeclaration => ZigElementType::FnDeclaration,
            T::VarDeclaration => ZigElementType::VarDeclaration,
            T::StructDeclaration => ZigElementType::StructDeclaration,
            T::EnumDeclaration => ZigElementType::EnumDeclaration,
            T::UnionDeclaration => ZigElementType::UnionDeclaration,
            T::Block => ZigElementType::Block,
            T::IfStatement => ZigElementType::IfStatement,
            T::WhileStatement => ZigElementType::WhileStatement,
            T::ForStatement => ZigElementType::ForStatement,
            T::ReturnStatement => ZigElementType::ReturnStatement,
        }
    }
}
