[package]
name = "oak-glob"
description = "Glob pattern language support for Oaks"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[features]
default = []
lsp = ["oak-lsp", "oak-highlight", "oak-pretty-print", "oak-formatter"]
oak-highlight = ["dep:oak-highlight"]
oak-pretty-print = ["dep:oak-pretty-print"]
oak-formatter = ["dep:oak-formatter"]
mcp = ["oak-mcp"]

[dependencies]
oak-core = { workspace = true }
oak-lsp = { workspace = true, optional = true }
oak-mcp = { workspace = true, optional = true }
oak-highlight = { workspace = true, optional = true }
oak-pretty-print = { workspace = true, optional = true }
oak-formatter = { workspace = true, optional = true }
