use oak_core::{ElementType, Parser, UniversalElementRole};
#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub enum VhdlElementType {
    // Tokens (mapped from VhdlTokenType)
    Error,
    Eof,
    Whitespace,
    Comment,
    Identifier,
    StringLiteral,
    CharLiteral,
    BitStringLiteral,
    BasedLiteral,
    RealLiteral,
    IntegerLiteral,
    EntityKw,
    ArchitectureKw,
    BeginKw,
    EndKw,
    ProcessKw,
    SignalKw,
    VariableKw,
    ConstantKw,
    ComponentKw,
    PortKw,
    MapKw,
    GenericKw,
    LibraryKw,
    UseKw,
    PackageKw,
    BodyKw,
    FunctionKw,
    ProcedureKw,
    TypeKw,
    SubtypeKw,
    RecordKw,
    ArrayKw,
    IfKw,
    ThenKw,
    ElseKw,
    ElsifKw,
    CaseKw,
    WhenKw,
    LoopKw,
    ForKw,
    WhileKw,
    ExitKw,
    NextKw,
    ReturnKw,
    WaitKw,
    UntilKw,
    InKw,
    OutKw,
    InoutKw,
    BufferKw,
    LinkageKw,
    DowntoKw,
    ToKw,
    GenerateKw,
    WithKw,
    SelectKw,
    AllKw,
    OthersKw,
    NullKw,
    OpenKw,
    IsKw,
    OfKw,
    RangeKw,
    ReverseRangeKw,
    AttributeKw,
    AliasKw,
    FileKw,
    AccessKw,
    AfterKw,
    AssertKw,
    ReportKw,
    SeverityKw,
    BitKw,
    BitVectorKw,
    BooleanKw,
    CharacterKw,
    IntegerKw,
    NaturalKw,
    PositiveKw,
    RealKw,
    StringKw,
    TimeKw,
    StdLogicKw,
    StdLogicVectorKw,
    UnsignedKw,
    SignedKw,
    And,
    Or,
    Nand,
    Nor,
    Xor,
    Xnor,
    Not,
    Sll,
    Srl,
    Sla,
    Sra,
    Rol,
    Ror,
    Mod,
    Rem,
    Abs,
    Arrow,
    Eq,
    Ne,
    Slash,
    Le,
    Lt,
    Ge,
    Gt,
    ShiftLeft,
    ShiftRight,
    Plus,
    Minus,
    Star,
    Pow,
    Assign,
    Colon,
    Ampersand,
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    Semicolon,
    Comma,
    Dot,
    Pipe,
    Hash,
    At,
    Question,
    Dollar,
    Percent,
    Caret,
    Tilde,
    Backslash,
    Exclamation,

    // Composite Elements
    Root,
    EntityDeclaration,
    ArchitectureBody,
    PackageDeclaration,
    PackageBody,
    ConfigurationDeclaration,
    LibraryClause,
    UseClause,
    GenericClause,
    PortClause,
    SignalDeclaration,
    VariableDeclaration,
    ConstantDeclaration,
    ProcessStatement,
    ComponentDeclaration,
    FunctionDeclaration,
    ProcedureDeclaration,
    TypeDeclaration,
    SubtypeDeclaration,
    IfStatement,
    CaseStatement,
    LoopStatement,
    AssignmentStatement,
    WaitStatement,
    AssertStatement,
    ReportStatement,
    AttributeDeclaration,
    AliasDeclaration,
    FileDeclaration,
    AccessDeclaration,
    GenerateStatement,
    BlockStatement,
    ComponentInstantiation,
}

impl ElementType for VhdlElementType {
    type Role = UniversalElementRole;

    fn role(&self) -> Self::Role {
        match self {
            _ => UniversalElementRole::None,
        }
    }
}

impl From<crate::lexer::token_type::VhdlTokenType> for VhdlElementType {
    fn from(token: crate::lexer::token_type::VhdlTokenType) -> Self {
        match token {
            crate::lexer::token_type::VhdlTokenType::Error => Self::Error,
            crate::lexer::token_type::VhdlTokenType::Eof => Self::Eof,
            crate::lexer::token_type::VhdlTokenType::Whitespace => Self::Whitespace,
            crate::lexer::token_type::VhdlTokenType::Comment => Self::Comment,
            crate::lexer::token_type::VhdlTokenType::Identifier => Self::Identifier,
            crate::lexer::token_type::VhdlTokenType::StringLiteral => Self::StringLiteral,
            crate::lexer::token_type::VhdlTokenType::CharLiteral => Self::CharLiteral,
            crate::lexer::token_type::VhdlTokenType::BitStringLiteral => Self::BitStringLiteral,
            crate::lexer::token_type::VhdlTokenType::BasedLiteral => Self::BasedLiteral,
            crate::lexer::token_type::VhdlTokenType::RealLiteral => Self::RealLiteral,
            crate::lexer::token_type::VhdlTokenType::IntegerLiteral => Self::IntegerLiteral,
            crate::lexer::token_type::VhdlTokenType::EntityKw => Self::EntityKw,
            crate::lexer::token_type::VhdlTokenType::ArchitectureKw => Self::ArchitectureKw,
            crate::lexer::token_type::VhdlTokenType::BeginKw => Self::BeginKw,
            crate::lexer::token_type::VhdlTokenType::EndKw => Self::EndKw,
            crate::lexer::token_type::VhdlTokenType::ProcessKw => Self::ProcessKw,
            crate::lexer::token_type::VhdlTokenType::SignalKw => Self::SignalKw,
            crate::lexer::token_type::VhdlTokenType::VariableKw => Self::VariableKw,
            crate::lexer::token_type::VhdlTokenType::ConstantKw => Self::ConstantKw,
            crate::lexer::token_type::VhdlTokenType::ComponentKw => Self::ComponentKw,
            crate::lexer::token_type::VhdlTokenType::PortKw => Self::PortKw,
            crate::lexer::token_type::VhdlTokenType::MapKw => Self::MapKw,
            crate::lexer::token_type::VhdlTokenType::GenericKw => Self::GenericKw,
            crate::lexer::token_type::VhdlTokenType::LibraryKw => Self::LibraryKw,
            crate::lexer::token_type::VhdlTokenType::UseKw => Self::UseKw,
            crate::lexer::token_type::VhdlTokenType::PackageKw => Self::PackageKw,
            crate::lexer::token_type::VhdlTokenType::BodyKw => Self::BodyKw,
            crate::lexer::token_type::VhdlTokenType::FunctionKw => Self::FunctionKw,
            crate::lexer::token_type::VhdlTokenType::ProcedureKw => Self::ProcedureKw,
            crate::lexer::token_type::VhdlTokenType::TypeKw => Self::TypeKw,
            crate::lexer::token_type::VhdlTokenType::SubtypeKw => Self::SubtypeKw,
            crate::lexer::token_type::VhdlTokenType::RecordKw => Self::RecordKw,
            crate::lexer::token_type::VhdlTokenType::ArrayKw => Self::ArrayKw,
            crate::lexer::token_type::VhdlTokenType::IfKw => Self::IfKw,
            crate::lexer::token_type::VhdlTokenType::ThenKw => Self::ThenKw,
            crate::lexer::token_type::VhdlTokenType::ElseKw => Self::ElseKw,
            crate::lexer::token_type::VhdlTokenType::ElsifKw => Self::ElsifKw,
            crate::lexer::token_type::VhdlTokenType::CaseKw => Self::CaseKw,
            crate::lexer::token_type::VhdlTokenType::WhenKw => Self::WhenKw,
            crate::lexer::token_type::VhdlTokenType::LoopKw => Self::LoopKw,
            crate::lexer::token_type::VhdlTokenType::ForKw => Self::ForKw,
            crate::lexer::token_type::VhdlTokenType::WhileKw => Self::WhileKw,
            crate::lexer::token_type::VhdlTokenType::ExitKw => Self::ExitKw,
            crate::lexer::token_type::VhdlTokenType::NextKw => Self::NextKw,
            crate::lexer::token_type::VhdlTokenType::ReturnKw => Self::ReturnKw,
            crate::lexer::token_type::VhdlTokenType::WaitKw => Self::WaitKw,
            crate::lexer::token_type::VhdlTokenType::UntilKw => Self::UntilKw,
            crate::lexer::token_type::VhdlTokenType::InKw => Self::InKw,
            crate::lexer::token_type::VhdlTokenType::OutKw => Self::OutKw,
            crate::lexer::token_type::VhdlTokenType::InoutKw => Self::InoutKw,
            crate::lexer::token_type::VhdlTokenType::BufferKw => Self::BufferKw,
            crate::lexer::token_type::VhdlTokenType::LinkageKw => Self::LinkageKw,
            crate::lexer::token_type::VhdlTokenType::DowntoKw => Self::DowntoKw,
            crate::lexer::token_type::VhdlTokenType::ToKw => Self::ToKw,
            crate::lexer::token_type::VhdlTokenType::GenerateKw => Self::GenerateKw,
            crate::lexer::token_type::VhdlTokenType::WithKw => Self::WithKw,
            crate::lexer::token_type::VhdlTokenType::SelectKw => Self::SelectKw,
            crate::lexer::token_type::VhdlTokenType::AllKw => Self::AllKw,
            crate::lexer::token_type::VhdlTokenType::OthersKw => Self::OthersKw,
            crate::lexer::token_type::VhdlTokenType::NullKw => Self::NullKw,
            crate::lexer::token_type::VhdlTokenType::OpenKw => Self::OpenKw,
            crate::lexer::token_type::VhdlTokenType::IsKw => Self::IsKw,
            crate::lexer::token_type::VhdlTokenType::OfKw => Self::OfKw,
            crate::lexer::token_type::VhdlTokenType::RangeKw => Self::RangeKw,
            crate::lexer::token_type::VhdlTokenType::ReverseRangeKw => Self::ReverseRangeKw,
            crate::lexer::token_type::VhdlTokenType::AttributeKw => Self::AttributeKw,
            crate::lexer::token_type::VhdlTokenType::AliasKw => Self::AliasKw,
            crate::lexer::token_type::VhdlTokenType::FileKw => Self::FileKw,
            crate::lexer::token_type::VhdlTokenType::AccessKw => Self::AccessKw,
            crate::lexer::token_type::VhdlTokenType::AfterKw => Self::AfterKw,
            crate::lexer::token_type::VhdlTokenType::AssertKw => Self::AssertKw,
            crate::lexer::token_type::VhdlTokenType::ReportKw => Self::ReportKw,
            crate::lexer::token_type::VhdlTokenType::SeverityKw => Self::SeverityKw,
            crate::lexer::token_type::VhdlTokenType::BitKw => Self::BitKw,
            crate::lexer::token_type::VhdlTokenType::BitVectorKw => Self::BitVectorKw,
            crate::lexer::token_type::VhdlTokenType::BooleanKw => Self::BooleanKw,
            crate::lexer::token_type::VhdlTokenType::CharacterKw => Self::CharacterKw,
            crate::lexer::token_type::VhdlTokenType::IntegerKw => Self::IntegerKw,
            crate::lexer::token_type::VhdlTokenType::NaturalKw => Self::NaturalKw,
            crate::lexer::token_type::VhdlTokenType::PositiveKw => Self::PositiveKw,
            crate::lexer::token_type::VhdlTokenType::RealKw => Self::RealKw,
            crate::lexer::token_type::VhdlTokenType::StringKw => Self::StringKw,
            crate::lexer::token_type::VhdlTokenType::TimeKw => Self::TimeKw,
            crate::lexer::token_type::VhdlTokenType::StdLogicKw => Self::StdLogicKw,
            crate::lexer::token_type::VhdlTokenType::StdLogicVectorKw => Self::StdLogicVectorKw,
            crate::lexer::token_type::VhdlTokenType::UnsignedKw => Self::UnsignedKw,
            crate::lexer::token_type::VhdlTokenType::SignedKw => Self::SignedKw,
            crate::lexer::token_type::VhdlTokenType::And => Self::And,
            crate::lexer::token_type::VhdlTokenType::Or => Self::Or,
            crate::lexer::token_type::VhdlTokenType::Nand => Self::Nand,
            crate::lexer::token_type::VhdlTokenType::Nor => Self::Nor,
            crate::lexer::token_type::VhdlTokenType::Xor => Self::Xor,
            crate::lexer::token_type::VhdlTokenType::Xnor => Self::Xnor,
            crate::lexer::token_type::VhdlTokenType::Not => Self::Not,
            crate::lexer::token_type::VhdlTokenType::Sll => Self::Sll,
            crate::lexer::token_type::VhdlTokenType::Srl => Self::Srl,
            crate::lexer::token_type::VhdlTokenType::Sla => Self::Sla,
            crate::lexer::token_type::VhdlTokenType::Sra => Self::Sra,
            crate::lexer::token_type::VhdlTokenType::Rol => Self::Rol,
            crate::lexer::token_type::VhdlTokenType::Ror => Self::Ror,
            crate::lexer::token_type::VhdlTokenType::Mod => Self::Mod,
            crate::lexer::token_type::VhdlTokenType::Rem => Self::Rem,
            crate::lexer::token_type::VhdlTokenType::Abs => Self::Abs,
            crate::lexer::token_type::VhdlTokenType::Arrow => Self::Arrow,
            crate::lexer::token_type::VhdlTokenType::Eq => Self::Eq,
            crate::lexer::token_type::VhdlTokenType::Ne => Self::Ne,
            crate::lexer::token_type::VhdlTokenType::Slash => Self::Slash,
            crate::lexer::token_type::VhdlTokenType::Le => Self::Le,
            crate::lexer::token_type::VhdlTokenType::Lt => Self::Lt,
            crate::lexer::token_type::VhdlTokenType::Ge => Self::Ge,
            crate::lexer::token_type::VhdlTokenType::Gt => Self::Gt,
            crate::lexer::token_type::VhdlTokenType::ShiftLeft => Self::ShiftLeft,
            crate::lexer::token_type::VhdlTokenType::ShiftRight => Self::ShiftRight,
            crate::lexer::token_type::VhdlTokenType::Plus => Self::Plus,
            crate::lexer::token_type::VhdlTokenType::Minus => Self::Minus,
            crate::lexer::token_type::VhdlTokenType::Star => Self::Star,
            crate::lexer::token_type::VhdlTokenType::Pow => Self::Pow,
            crate::lexer::token_type::VhdlTokenType::Assign => Self::Assign,
            crate::lexer::token_type::VhdlTokenType::Colon => Self::Colon,
            crate::lexer::token_type::VhdlTokenType::Ampersand => Self::Ampersand,
            crate::lexer::token_type::VhdlTokenType::LeftParen => Self::LeftParen,
            crate::lexer::token_type::VhdlTokenType::RightParen => Self::RightParen,
            crate::lexer::token_type::VhdlTokenType::LeftBracket => Self::LeftBracket,
            crate::lexer::token_type::VhdlTokenType::RightBracket => Self::RightBracket,
            crate::lexer::token_type::VhdlTokenType::Semicolon => Self::Semicolon,
            crate::lexer::token_type::VhdlTokenType::Comma => Self::Comma,
            crate::lexer::token_type::VhdlTokenType::Dot => Self::Dot,
            crate::lexer::token_type::VhdlTokenType::Pipe => Self::Pipe,
            crate::lexer::token_type::VhdlTokenType::Hash => Self::Hash,
            crate::lexer::token_type::VhdlTokenType::At => Self::At,
            crate::lexer::token_type::VhdlTokenType::Question => Self::Question,
            crate::lexer::token_type::VhdlTokenType::Dollar => Self::Dollar,
            crate::lexer::token_type::VhdlTokenType::Percent => Self::Percent,
            crate::lexer::token_type::VhdlTokenType::Caret => Self::Caret,
            crate::lexer::token_type::VhdlTokenType::Tilde => Self::Tilde,
            crate::lexer::token_type::VhdlTokenType::Backslash => Self::Backslash,
            crate::lexer::token_type::VhdlTokenType::Exclamation => Self::Exclamation,
        }
    }
}
