use oak_core::{ElementType, UniversalElementRole};
#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[repr(u8)]
pub enum SwiftElementType {
    Whitespace,
    Newline,
    Comment,
    Identifier,
    Error,
    Eof,
    NumberLiteral,
    StringLiteral,
    CharLiteral,
    BooleanLiteral,
    Class,
    Struct,
    Enum,
    Protocol,
    Extension,
    Func,
    Var,
    Let,
    Init,
    Deinit,
    Subscript,
    Typealias,
    Import,
    If,
    Else,
    Switch,
    Case,
    Default,
    For,
    While,
    Repeat,
    Do,
    Break,
    Continue,
    Fallthrough,
    Return,
    Throw,
    Try,
    Catch,
    Finally,
    Guard,
    Defer,
    Public,
    Private,
    Internal,
    Fileprivate,
    Open,
    Static,
    Final,
    Override,
    Mutating,
    Nonmutating,
    Lazy,
    Weak,
    Unowned,
    Optional,
    Required,
    Convenience,
    Dynamic,
    Infix,
    Prefix,
    Postfix,
    Any,
    AnyObject,
    Self_,
    Type,
    Protocol_,
    True,
    False,
    Nil,
    As,
    Is,
    In,
    Where,
    Associatedtype,
    Operator,
    Precedencegroup,
    Indirect,
    Rethrows,
    Throws,
    Inout,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Equal,
    NotEqual,
    Less,
    Greater,
    LessEqual,
    GreaterEqual,
    LogicalAnd,
    LogicalOr,
    LogicalNot,
    BitAnd,
    BitOr,
    BitXor,
    BitNot,
    LeftShift,
    RightShift,
    Assign,
    PlusAssign,
    MinusAssign,
    StarAssign,
    SlashAssign,
    PercentAssign,
    AndAssign,
    OrAssign,
    XorAssign,
    LeftShiftAssign,
    RightShiftAssign,
    Question,
    QuestionQuestion,
    Dot,
    Arrow,
    Range,
    ClosedRange,
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    LeftBrace,
    RightBrace,
    Comma,
    Semicolon,
    Colon,
    At,
    Hash,
    Dollar,
    Underscore,
    Backslash,
    SourceFile,
    FunctionDeclaration,
    Parameter,
    ParameterList,
    VariableDeclaration,
    ClassDeclaration,
    StructDeclaration,
    EnumDeclaration,
    ProtocolDeclaration,
    IfStatement,
    WhileStatement,
    ForStatement,
    ReturnStatement,
    BreakStatement,
    ContinueStatement,
    ExpressionStatement,
    Block,
    BinaryExpression,
    UnaryExpression,
    CallExpression,
    MemberExpression,
    IdentifierExpression,
    LiteralExpression,
}

impl SwiftElementType {
    pub fn is_trivia(&self) -> bool {
        matches!(self, Self::Whitespace | Self::Newline | Self::Comment)
    }
}

impl ElementType for SwiftElementType {
    type Role = UniversalElementRole;

    fn role(&self) -> Self::Role {
        match self {
            Self::SourceFile => UniversalElementRole::Root,
            Self::Error => UniversalElementRole::Error,
            _ => UniversalElementRole::None,
        }
    }
}

impl From<crate::lexer::token_type::SwiftTokenType> for SwiftElementType {
    fn from(token: crate::lexer::token_type::SwiftTokenType) -> Self {
        use crate::lexer::token_type::SwiftTokenType as T;
        match token {
            T::Whitespace => Self::Whitespace,
            T::Newline => Self::Newline,
            T::Comment => Self::Comment,
            T::Identifier => Self::Identifier,
            T::Error => Self::Error,
            T::Eof => Self::Eof,
            T::NumberLiteral => Self::NumberLiteral,
            T::StringLiteral => Self::StringLiteral,
            T::CharLiteral => Self::CharLiteral,
            T::BooleanLiteral => Self::BooleanLiteral,
            T::Class => Self::Class,
            T::Struct => Self::Struct,
            T::Enum => Self::Enum,
            T::Protocol => Self::Protocol,
            T::Extension => Self::Extension,
            T::Func => Self::Func,
            T::Var => Self::Var,
            T::Let => Self::Let,
            T::Init => Self::Init,
            T::Deinit => Self::Deinit,
            T::Subscript => Self::Subscript,
            T::Typealias => Self::Typealias,
            T::Import => Self::Import,
            T::If => Self::If,
            T::Else => Self::Else,
            T::Switch => Self::Switch,
            T::Case => Self::Case,
            T::Default => Self::Default,
            T::For => Self::For,
            T::While => Self::While,
            T::Repeat => Self::Repeat,
            T::Do => Self::Do,
            T::Break => Self::Break,
            T::Continue => Self::Continue,
            T::Fallthrough => Self::Fallthrough,
            T::Return => Self::Return,
            T::Throw => Self::Throw,
            T::Try => Self::Try,
            T::Catch => Self::Catch,
            T::Finally => Self::Finally,
            T::Guard => Self::Guard,
            T::Defer => Self::Defer,
            T::Public => Self::Public,
            T::Private => Self::Private,
            T::Internal => Self::Internal,
            T::Fileprivate => Self::Fileprivate,
            T::Open => Self::Open,
            T::Static => Self::Static,
            T::Final => Self::Final,
            T::Override => Self::Override,
            T::Mutating => Self::Mutating,
            T::Nonmutating => Self::Nonmutating,
            T::Lazy => Self::Lazy,
            T::Weak => Self::Weak,
            T::Unowned => Self::Unowned,
            T::Optional => Self::Optional,
            T::Required => Self::Required,
            T::Convenience => Self::Convenience,
            T::Dynamic => Self::Dynamic,
            T::Infix => Self::Infix,
            T::Prefix => Self::Prefix,
            T::Postfix => Self::Postfix,
            T::Any => Self::Any,
            T::AnyObject => Self::AnyObject,
            T::Self_ => Self::Self_,
            T::Type => Self::Type,
            T::Protocol_ => Self::Protocol_,
            T::True => Self::True,
            T::False => Self::False,
            T::Nil => Self::Nil,
            T::As => Self::As,
            T::Is => Self::Is,
            T::In => Self::In,
            T::Where => Self::Where,
            T::Associatedtype => Self::Associatedtype,
            T::Operator => Self::Operator,
            T::Precedencegroup => Self::Precedencegroup,
            T::Indirect => Self::Indirect,
            T::Rethrows => Self::Rethrows,
            T::Throws => Self::Throws,
            T::Inout => Self::Inout,
            T::Plus => Self::Plus,
            T::Minus => Self::Minus,
            T::Star => Self::Star,
            T::Slash => Self::Slash,
            T::Percent => Self::Percent,
            T::Equal => Self::Equal,
            T::NotEqual => Self::NotEqual,
            T::Less => Self::Less,
            T::Greater => Self::Greater,
            T::LessEqual => Self::LessEqual,
            T::GreaterEqual => Self::GreaterEqual,
            T::LogicalAnd => Self::LogicalAnd,
            T::LogicalOr => Self::LogicalOr,
            T::LogicalNot => Self::LogicalNot,
            T::BitAnd => Self::BitAnd,
            T::BitOr => Self::BitOr,
            T::BitXor => Self::BitXor,
            T::BitNot => Self::BitNot,
            T::LeftShift => Self::LeftShift,
            T::RightShift => Self::RightShift,
            T::Assign => Self::Assign,
            T::PlusAssign => Self::PlusAssign,
            T::MinusAssign => Self::MinusAssign,
            T::StarAssign => Self::StarAssign,
            T::SlashAssign => Self::SlashAssign,
            T::PercentAssign => Self::PercentAssign,
            T::AndAssign => Self::AndAssign,
            T::OrAssign => Self::OrAssign,
            T::XorAssign => Self::XorAssign,
            T::LeftShiftAssign => Self::LeftShiftAssign,
            T::RightShiftAssign => Self::RightShiftAssign,
            T::Question => Self::Question,
            T::QuestionQuestion => Self::QuestionQuestion,
            T::Dot => Self::Dot,
            T::Arrow => Self::Arrow,
            T::Range => Self::Range,
            T::ClosedRange => Self::ClosedRange,
            T::LeftParen => Self::LeftParen,
            T::RightParen => Self::RightParen,
            T::LeftBracket => Self::LeftBracket,
            T::RightBracket => Self::RightBracket,
            T::LeftBrace => Self::LeftBrace,
            T::RightBrace => Self::RightBrace,
            T::Comma => Self::Comma,
            T::Semicolon => Self::Semicolon,
            T::Colon => Self::Colon,
            T::At => Self::At,
            T::Hash => Self::Hash,
            T::Dollar => Self::Dollar,
            T::Underscore => Self::Underscore,
            T::Backslash => Self::Backslash,
            T::SourceFile => Self::SourceFile,
            T::FunctionDeclaration => Self::FunctionDeclaration,
            T::Parameter => Self::Parameter,
            T::ParameterList => Self::ParameterList,
            T::VariableDeclaration => Self::VariableDeclaration,
            T::ClassDeclaration => Self::ClassDeclaration,
            T::StructDeclaration => Self::StructDeclaration,
            T::EnumDeclaration => Self::EnumDeclaration,
            T::ProtocolDeclaration => Self::ProtocolDeclaration,
            T::IfStatement => Self::IfStatement,
            T::WhileStatement => Self::WhileStatement,
            T::ForStatement => Self::ForStatement,
            T::ReturnStatement => Self::ReturnStatement,
            T::BreakStatement => Self::BreakStatement,
            T::ContinueStatement => Self::ContinueStatement,
            T::ExpressionStatement => Self::ExpressionStatement,
            T::Block => Self::Block,
            T::BinaryExpression => Self::BinaryExpression,
            T::UnaryExpression => Self::UnaryExpression,
            T::CallExpression => Self::CallExpression,
            T::MemberExpression => Self::MemberExpression,
            T::IdentifierExpression => Self::IdentifierExpression,
            T::LiteralExpression => Self::LiteralExpression,
        }
    }
}
