use oak_core::{ElementType, UniversalElementRole};
#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub enum KotlinElementType {
    // Structural nodes
    SourceFile,
    ClassDeclaration,
    FunctionDeclaration,
    VariableDeclaration,
    IfStatement,
    WhileStatement,
    ReturnStatement,
    Block,
    Parameter,
    Identifier,
    IntLiteral,
    PrefixExpression,
    MemberAccessExpression,
    CallExpression,
    AssignmentExpression,
    BinaryExpression,
    Error,

    // Mirrored token kinds (for leaf elements and completeness)
    Root,
    EndOfStream,
    UnaryExpression,
    LiteralExpression,
    IdentifierExpression,
    TypeReference,
    Class,
    Fun,
    Val,
    Var,
    If,
    Else,
    When,
    For,
    While,
    Return,
    Break,
    Continue,
    Try,
    Catch,
    Finally,
    Throw,
    Import,
    Package,
    Public,
    Private,
    Protected,
    Internal,
    Abstract,
    Final,
    Open,
    Override,
    Companion,
    Object,
    Interface,
    Enum,
    Data,
    Sealed,
    Inline,
    Suspend,
    Operator,
    Infix,
    Tailrec,
    External,
    Annotation,
    Crossinline,
    Noinline,
    Reified,
    Vararg,
    Out,
    In,
    Is,
    As,
    This,
    Super,
    Null,
    True,
    False,
    Keyword,
    StringLiteral,
    CharLiteral,
    NumberLiteral,
    FloatLiteral,
    BooleanLiteral,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Equals,
    Less,
    Greater,
    Ampersand,
    Pipe,
    Caret,
    Tilde,
    Exclamation,
    Assign,
    PlusAssign,
    MinusAssign,
    StarAssign,
    SlashAssign,
    PercentAssign,
    EqEq,
    NotEq,
    Lt,
    Gt,
    LtEq,
    GtEq,
    AndAnd,
    OrOr,
    Dot,
    Comma,
    Colon,
    Semi,
    Arrow,
    DoubleColon,
    Range,
    Question,
    ExclamationExclamation,
    At,
    LParen,
    RParen,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    Comment,
    Whitespace,
    Newline,
}

impl ElementType for KotlinElementType {
    type Role = UniversalElementRole;

    fn role(&self) -> Self::Role {
        match self {
            KotlinElementType::SourceFile | KotlinElementType::Root => UniversalElementRole::Root,
            KotlinElementType::ClassDeclaration | KotlinElementType::FunctionDeclaration => UniversalElementRole::Definition,
            KotlinElementType::VariableDeclaration | KotlinElementType::IfStatement | KotlinElementType::WhileStatement | KotlinElementType::ReturnStatement | KotlinElementType::Block => UniversalElementRole::Statement,
            KotlinElementType::Error => UniversalElementRole::Error,
            _ => UniversalElementRole::None,
        }
    }
}

impl From<crate::lexer::token_type::KotlinTokenType> for KotlinElementType {
    fn from(token: crate::lexer::token_type::KotlinTokenType) -> Self {
        use crate::lexer::token_type::KotlinTokenType as T;
        match token {
            T::Root => KotlinElementType::Root,
            T::SourceFile => KotlinElementType::SourceFile,
            T::EndOfStream => KotlinElementType::EndOfStream,
            T::FunctionDeclaration => KotlinElementType::FunctionDeclaration,
            T::ClassDeclaration => KotlinElementType::ClassDeclaration,
            T::VariableDeclaration => KotlinElementType::VariableDeclaration,
            T::IfStatement => KotlinElementType::IfStatement,
            T::WhileStatement => KotlinElementType::WhileStatement,
            T::ReturnStatement => KotlinElementType::ReturnStatement,
            T::Block => KotlinElementType::Block,
            T::BinaryExpression => KotlinElementType::BinaryExpression,
            T::UnaryExpression => KotlinElementType::UnaryExpression,
            T::AssignmentExpression => KotlinElementType::AssignmentExpression,
            T::CallExpression => KotlinElementType::CallExpression,
            T::MemberAccessExpression => KotlinElementType::MemberAccessExpression,
            T::LiteralExpression => KotlinElementType::LiteralExpression,
            T::IdentifierExpression => KotlinElementType::IdentifierExpression,
            T::Parameter => KotlinElementType::Parameter,
            T::TypeReference => KotlinElementType::TypeReference,
            T::Class => KotlinElementType::Class,
            T::Fun => KotlinElementType::Fun,
            T::Val => KotlinElementType::Val,
            T::Var => KotlinElementType::Var,
            T::If => KotlinElementType::If,
            T::Else => KotlinElementType::Else,
            T::When => KotlinElementType::When,
            T::For => KotlinElementType::For,
            T::While => KotlinElementType::While,
            T::Return => KotlinElementType::Return,
            T::Break => KotlinElementType::Break,
            T::Continue => KotlinElementType::Continue,
            T::Try => KotlinElementType::Try,
            T::Catch => KotlinElementType::Catch,
            T::Finally => KotlinElementType::Finally,
            T::Throw => KotlinElementType::Throw,
            T::Import => KotlinElementType::Import,
            T::Package => KotlinElementType::Package,
            T::Public => KotlinElementType::Public,
            T::Private => KotlinElementType::Private,
            T::Protected => KotlinElementType::Protected,
            T::Internal => KotlinElementType::Internal,
            T::Abstract => KotlinElementType::Abstract,
            T::Final => KotlinElementType::Final,
            T::Open => KotlinElementType::Open,
            T::Override => KotlinElementType::Override,
            T::Companion => KotlinElementType::Companion,
            T::Object => KotlinElementType::Object,
            T::Interface => KotlinElementType::Interface,
            T::Enum => KotlinElementType::Enum,
            T::Data => KotlinElementType::Data,
            T::Sealed => KotlinElementType::Sealed,
            T::Inline => KotlinElementType::Inline,
            T::Suspend => KotlinElementType::Suspend,
            T::Operator => KotlinElementType::Operator,
            T::Infix => KotlinElementType::Infix,
            T::Tailrec => KotlinElementType::Tailrec,
            T::External => KotlinElementType::External,
            T::Annotation => KotlinElementType::Annotation,
            T::Crossinline => KotlinElementType::Crossinline,
            T::Noinline => KotlinElementType::Noinline,
            T::Reified => KotlinElementType::Reified,
            T::Vararg => KotlinElementType::Vararg,
            T::Out => KotlinElementType::Out,
            T::In => KotlinElementType::In,
            T::Is => KotlinElementType::Is,
            T::As => KotlinElementType::As,
            T::This => KotlinElementType::This,
            T::Super => KotlinElementType::Super,
            T::Null => KotlinElementType::Null,
            T::True => KotlinElementType::True,
            T::False => KotlinElementType::False,
            T::Identifier => KotlinElementType::Identifier,
            T::Keyword => KotlinElementType::Keyword,
            T::StringLiteral => KotlinElementType::StringLiteral,
            T::CharLiteral => KotlinElementType::CharLiteral,
            T::NumberLiteral => KotlinElementType::NumberLiteral,
            T::IntLiteral => KotlinElementType::IntLiteral,
            T::FloatLiteral => KotlinElementType::FloatLiteral,
            T::BooleanLiteral => KotlinElementType::BooleanLiteral,
            T::Plus => KotlinElementType::Plus,
            T::Minus => KotlinElementType::Minus,
            T::Star => KotlinElementType::Star,
            T::Slash => KotlinElementType::Slash,
            T::Percent => KotlinElementType::Percent,
            T::Equals => KotlinElementType::Equals,
            T::Less => KotlinElementType::Less,
            T::Greater => KotlinElementType::Greater,
            T::Ampersand => KotlinElementType::Ampersand,
            T::Pipe => KotlinElementType::Pipe,
            T::Caret => KotlinElementType::Caret,
            T::Tilde => KotlinElementType::Tilde,
            T::Exclamation => KotlinElementType::Exclamation,
            T::Assign => KotlinElementType::Assign,
            T::PlusAssign => KotlinElementType::PlusAssign,
            T::MinusAssign => KotlinElementType::MinusAssign,
            T::StarAssign => KotlinElementType::StarAssign,
            T::SlashAssign => KotlinElementType::SlashAssign,
            T::PercentAssign => KotlinElementType::PercentAssign,
            T::EqEq => KotlinElementType::EqEq,
            T::NotEq => KotlinElementType::NotEq,
            T::Lt => KotlinElementType::Lt,
            T::Gt => KotlinElementType::Gt,
            T::LtEq => KotlinElementType::LtEq,
            T::GtEq => KotlinElementType::GtEq,
            T::AndAnd => KotlinElementType::AndAnd,
            T::OrOr => KotlinElementType::OrOr,
            T::Dot => KotlinElementType::Dot,
            T::Comma => KotlinElementType::Comma,
            T::Colon => KotlinElementType::Colon,
            T::Semi => KotlinElementType::Semi,
            T::Arrow => KotlinElementType::Arrow,
            T::DoubleColon => KotlinElementType::DoubleColon,
            T::Range => KotlinElementType::Range,
            T::Question => KotlinElementType::Question,
            T::ExclamationExclamation => KotlinElementType::ExclamationExclamation,
            T::At => KotlinElementType::At,
            T::LParen => KotlinElementType::LParen,
            T::RParen => KotlinElementType::RParen,
            T::LBracket => KotlinElementType::LBracket,
            T::RBracket => KotlinElementType::RBracket,
            T::LBrace => KotlinElementType::LBrace,
            T::RBrace => KotlinElementType::RBrace,
            T::Comment => KotlinElementType::Comment,
            T::Whitespace => KotlinElementType::Whitespace,
            T::Newline => KotlinElementType::Newline,
            T::Error => KotlinElementType::Error,
        }
    }
}
