[package]
name = "oak-kotlin"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository = "https://github.com/nyar-vm/oaks"
homepage = "https://gaia-assembly.netlify.app/"
description = "Kotlin language support for Oak"

[dependencies]
oak-core = { workspace = true }
serde = { workspace = true, optional = true, features = ["derive"] }

[features]
serde = ["oak-core/serde", "dep:serde"]

[[test]]
name = "main"
required-features = ["serde"]
