[package]
name = "oak-kotlin"
version = "0.0.7"
edition = "2024"
authors = ["Gaia Team <192607617@qq.com>"]
license = "MPL-2.0"
repository = "https://github.com/nyar-vm/oaks"
homepage = "https://gaia-assembly.netlify.app/"
description = "Kotlin language support for Oak"

[dependencies]
oak-core = { workspace = true }
serde = { workspace = true, optional = true, features = ["derive"] }

[features]
serde = ["oak-core/serde", "dep:serde"]
