use oak_core::{ElementType, Parser, UniversalElementRole};
#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub enum DElementType {
    Root,
    Module,
    Declaration,
    Statement,
    Expression,
    Type,
    Aggregate,
    Import,
    ModuleKeyword,
    ImportKeyword,
    PublicKeyword,
    PrivateKeyword,
    ProtectedKeyword,
    PackageKeyword,
    ExportKeyword,
    StaticKeyword,
    FinalKeyword,
    AbstractKeyword,
    OverrideKeyword,
    SynchronizedKeyword,
    ConstKeyword,
    ImmutableKeyword,
    InoutKeyword,
    SharedKeyword,
    ClassKeyword,
    StructKeyword,
    InterfaceKeyword,
    UnionKeyword,
    EnumKeyword,
    FunctionKeyword,
    DelegateKeyword,
    IfKeyword,
    ElseKeyword,
    WhileKeyword,
    ForKeyword,
    ForeachKeyword,
    DoKeyword,
    SwitchKeyword,
    CaseKeyword,
    DefaultKeyword,
    BreakKeyword,
    ContinueKeyword,
    ReturnKeyword,
    GotoKeyword,
    TryKeyword,
    CatchKeyword,
    FinallyKeyword,
    ThrowKeyword,
    ScopeKeyword,
    WithKeyword,
    SynchronizedKeyword2,
    AsmKeyword,
    MixinKeyword,
    TemplateKeyword,
    ThisKeyword,
    SuperKeyword,
    NullKeyword,
    TrueKeyword,
    FalseKeyword,
    CastKeyword,
    NewKeyword,
    DeleteKeyword,
    TypeofKeyword,
    TypeidKeyword,
    IsKeyword,
    InKeyword,
    OutKeyword,
    RefKeyword,
    LazyKeyword,
    AutoKeyword,
    AliasKeyword,
    TypedefKeyword,
    ExternKeyword,
    PureKeyword,
    NothrowKeyword,
    SafeKeyword,
    TrustedKeyword,
    SystemKeyword,
    NogcKeyword,
    PropertyKeyword,
    DisableKeyword,
    DeprecatedKeyword,
    VersionKeyword,
    DebugKeyword,
    UnitTestKeyword,
    InvariantKeyword,
    BodyKeyword,
    PragmaKeyword,
    AlignKeyword,
    VoidType,
    BoolType,
    ByteType,
    UbyteType,
    ShortType,
    UshortType,
    IntType,
    UintType,
    LongType,
    UlongType,
    CentType,
    UcentType,
    FloatType,
    DoubleType,
    RealType,
    IfloatType,
    IdoubleType,
    IrealType,
    CfloatType,
    CdoubleType,
    CrealType,
    CharType,
    WcharType,
    DcharType,
    StringType,
    WstringType,
    DstringType,
    Plus,
    Minus,
    Multiply,
    Divide,
    Modulo,
    BitwiseAnd,
    BitwiseOr,
    BitwiseXor,
    BitwiseNot,
    LeftShift,
    RightShift,
    UnsignedRightShift,
    Equal,
    NotEqual,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    Identity,
    NotIdentity,
    Assign,
    PlusAssign,
    MinusAssign,
    MultiplyAssign,
    DivideAssign,
    ModuloAssign,
    BitwiseAndAssign,
    BitwiseOrAssign,
    BitwiseXorAssign,
    LeftShiftAssign,
    RightShiftAssign,
    UnsignedRightShiftAssign,
    ConcatenateAssign,
    LogicalAnd,
    LogicalOr,
    Increment,
    Decrement,
    Not,
    Question,
    Dollar,
    At,
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    LeftBrace,
    RightBrace,
    Semicolon,
    Comma,
    Dot,
    DotDot,
    DotDotDot,
    Colon,
    Arrow,
    Hash,
    IntegerLiteral,
    FloatLiteral,
    StringLiteral,
    CharLiteral,
    Identifier,
    LineComment,
    BlockComment,
    NestedComment,
    Whitespace,
    Newline,
    Eof,
    Error,
}

impl ElementType for DElementType {
    type Role = UniversalElementRole;

    fn role(&self) -> Self::Role {
        match self {
            Self::Root => UniversalElementRole::Root,

            Self::Error => UniversalElementRole::Error,
            _ => UniversalElementRole::None,
        }
    }
}

impl From<crate::lexer::token_type::DTokenType> for DElementType {
    fn from(token: crate::lexer::token_type::DTokenType) -> Self {
        unsafe { std::mem::transmute(token) }
    }
}
