[package]
name = "oak-fluent"
version = "0.0.9"
edition = { workspace = true }
authors = { workspace = true }
description = "Fluent internationalization support for oak framework"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
oak-core = { workspace = true }

[dev-dependencies]
assert_matches = "1.5"
