[package]
name = "oak-racket"
version.workspace = true
authors.workspace = true
description = "Hand-written Racket frontend"
edition.workspace = true
license.workspace = true
repository = "https://github.com/ygg-lang/oaks/tree/master/examples/oak-racket"
categories = ["compilers", "development-tools"]
keywords = ["frontend", "language", "racket"]

[dependencies]
oak-core = { workspace = true }
serde = { workspace = true, optional = true, features = ["derive"] }

[features]
serde = ["oak-core/serde", "dep:serde"]

[dev-dependencies]
oak-testing = { workspace = true }
