use oak_core::{ElementType, UniversalElementRole};
#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[repr(u8)]
pub enum TexElementType {
    // Node types
    Root,
    SourceFile,
    Document,

    // TeX commands and environments
    Command,
    Environment,
    BeginEnvironment,
    EndEnvironment,

    // TeX special structures
    MathMode,
    InlineMath,
    DisplayMath,
    Group,
    Superscript,
    Subscript,

    // Arguments and options
    Argument,
    OptionalArgument,
    MandatoryArgument,

    // Text and content
    Text,
    Paragraph,
    Section,
    Subsection,
    Subsubsection,

    // Lists and tables
    List,
    Item,
    Table,
    Row,
    Cell,

    // References and labels
    Label,
    Reference,
    Citation,

    // Figures and floats
    Figure,
    Caption,

    // Error nodes
    Error,

    // TeX keywords and commands
    DocumentClass,
    UsePackage,
    Begin,
    End,
    Section_,
    Subsection_,
    Subsubsection_,
    Chapter,
    Part,
    Title,
    Author,
    Date,
    MakeTitle,
    TableOfContents,
    NewPage,
    ClearPage,

    // Mathematical commands
    Frac,
    Sqrt,
    Sum,
    Int,
    Lim,
    Alpha,
    Beta,
    Gamma,
    Delta,
    Epsilon,
    Zeta,
    Eta,
    Theta,
    Iota,
    Kappa,
    Lambda,
    Mu,
    Nu,
    Xi,
    Omicron,
    Pi,
    Rho,
    Sigma,
    Tau,
    Upsilon,
    Phi,
    Chi,
    Psi,
    Omega,
    VarEpsilon,
    VarTheta,
    VarKappa,
    VarPi,
    VarRho,
    VarSigma,
    VarPhi,
    UpperGamma,
    UpperDelta,
    UpperTheta,
    UpperLambda,
    UpperXi,
    UpperPi,
    UpperSigma,
    UpperUpsilon,
    UpperPhi,
    UpperPsi,
    UpperOmega,

    // Formatting commands
    TextBf,
    TextIt,
    TextSc,
    TextTt,
    Emph,
    Underline,

    // Identifiers and literals
    Identifier,
    StringLiteral,
    Number,

    // Operators and punctuation
    Backslash,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    LeftParen,
    RightParen,
    Dollar,
    DoubleDollar,
    Ampersand,
    Percent,
    Hash,
    Caret,
    Underscore,
    Tilde,

    // Special characters
    Equal,
    Equals,
    Plus,
    Minus,
    Star,
    Slash,
    Pipe,
    Less,
    LessThan,
    Greater,
    GreaterThan,
    Exclamation,
    Question,
    At,
    Colon,
    Semicolon,
    Comma,
    Dot,

    // Whitespace and comments
    Comment,
    Whitespace,
    Newline,

    // Keywords
    BeginKeyword,
    EndKeyword,
    DocumentclassKeyword,
    UsepackageKeyword,
    SectionKeyword,
    SubsectionKeyword,
    SubsubsectionKeyword,
    ChapterKeyword,
    PartKeyword,
    TitleKeyword,
    AuthorKeyword,
    DateKeyword,
    MaketitleKeyword,
    TableofcontentsKeyword,
    ItemKeyword,
    LabelKeyword,
    RefKeyword,
    CiteKeyword,
    IncludegraphicsKeyword,
    TextbfKeyword,
    TextitKeyword,
    EmphKeyword,

    // End of file
    Eof,
}

impl ElementType for TexElementType {
    type Role = UniversalElementRole;

    fn role(&self) -> Self::Role {
        match self {
            _ => UniversalElementRole::None,
        }
    }
}

impl oak_core::language::TokenType for TexElementType {
    type Role = oak_core::UniversalTokenRole;
    const END_OF_STREAM: Self = Self::Eof;

    fn is_ignored(&self) -> bool {
        matches!(self, Self::Whitespace | Self::Newline | Self::Comment)
    }

    fn role(&self) -> Self::Role {
        match self {
            Self::Whitespace | Self::Newline => oak_core::UniversalTokenRole::Whitespace,
            Self::Comment => oak_core::UniversalTokenRole::Comment,
            Self::Eof => oak_core::UniversalTokenRole::Eof,
            Self::Error => oak_core::UniversalTokenRole::Error,
            _ => oak_core::UniversalTokenRole::None,
        }
    }
}

impl From<crate::lexer::token_type::TexTokenType> for TexElementType {
    fn from(token: crate::lexer::token_type::TexTokenType) -> Self {
        use crate::lexer::token_type::TexTokenType as T;
        match token {
            T::Root => Self::Root,
            T::SourceFile => Self::SourceFile,
            T::Document => Self::Document,
            T::Command => Self::Command,
            T::Environment => Self::Environment,
            T::BeginEnvironment => Self::BeginEnvironment,
            T::EndEnvironment => Self::EndEnvironment,
            T::MathMode => Self::MathMode,
            T::InlineMath => Self::InlineMath,
            T::DisplayMath => Self::DisplayMath,
            T::Group => Self::Group,
            T::Superscript => Self::Superscript,
            T::Subscript => Self::Subscript,
            T::Argument => Self::Argument,
            T::OptionalArgument => Self::OptionalArgument,
            T::MandatoryArgument => Self::MandatoryArgument,
            T::Text => Self::Text,
            T::Paragraph => Self::Paragraph,
            T::Section => Self::Section,
            T::Subsection => Self::Subsection,
            T::Subsubsection => Self::Subsubsection,
            T::List => Self::List,
            T::Item => Self::Item,
            T::Table => Self::Table,
            T::Row => Self::Row,
            T::Cell => Self::Cell,
            T::Label => Self::Label,
            T::Reference => Self::Reference,
            T::Citation => Self::Citation,
            T::Figure => Self::Figure,
            T::Caption => Self::Caption,
            T::Error => Self::Error,
            T::DocumentClass => Self::DocumentClass,
            T::UsePackage => Self::UsePackage,
            T::Begin => Self::Begin,
            T::End => Self::End,
            T::Section_ => Self::Section_,
            T::Subsection_ => Self::Subsection_,
            T::Subsubsection_ => Self::Subsubsection_,
            T::Chapter => Self::Chapter,
            T::Part => Self::Part,
            T::Title => Self::Title,
            T::Author => Self::Author,
            T::Date => Self::Date,
            T::MakeTitle => Self::MakeTitle,
            T::TableOfContents => Self::TableOfContents,
            T::NewPage => Self::NewPage,
            T::ClearPage => Self::ClearPage,
            T::Frac => Self::Frac,
            T::Sqrt => Self::Sqrt,
            T::Sum => Self::Sum,
            T::Int => Self::Int,
            T::Lim => Self::Lim,
            T::Alpha => Self::Alpha,
            T::Beta => Self::Beta,
            T::Gamma => Self::Gamma,
            T::Delta => Self::Delta,
            T::Epsilon => Self::Epsilon,
            T::Zeta => Self::Zeta,
            T::Eta => Self::Eta,
            T::Theta => Self::Theta,
            T::Iota => Self::Iota,
            T::Kappa => Self::Kappa,
            T::Lambda => Self::Lambda,
            T::Mu => Self::Mu,
            T::Nu => Self::Nu,
            T::Xi => Self::Xi,
            T::Omicron => Self::Omicron,
            T::Pi => Self::Pi,
            T::Rho => Self::Rho,
            T::Sigma => Self::Sigma,
            T::Tau => Self::Tau,
            T::Upsilon => Self::Upsilon,
            T::Phi => Self::Phi,
            T::Chi => Self::Chi,
            T::Psi => Self::Psi,
            T::Omega => Self::Omega,
            T::VarEpsilon => Self::VarEpsilon,
            T::VarTheta => Self::VarTheta,
            T::VarKappa => Self::VarKappa,
            T::VarPi => Self::VarPi,
            T::VarRho => Self::VarRho,
            T::VarSigma => Self::VarSigma,
            T::VarPhi => Self::VarPhi,
            T::UpperGamma => Self::UpperGamma,
            T::UpperDelta => Self::UpperDelta,
            T::UpperTheta => Self::UpperTheta,
            T::UpperLambda => Self::UpperLambda,
            T::UpperXi => Self::UpperXi,
            T::UpperPi => Self::UpperPi,
            T::UpperSigma => Self::UpperSigma,
            T::UpperUpsilon => Self::UpperUpsilon,
            T::UpperPhi => Self::UpperPhi,
            T::UpperPsi => Self::UpperPsi,
            T::UpperOmega => Self::UpperOmega,
            T::TextBf => Self::TextBf,
            T::TextIt => Self::TextIt,
            T::TextSc => Self::TextSc,
            T::TextTt => Self::TextTt,
            T::Emph => Self::Emph,
            T::Underline => Self::Underline,
            T::Identifier => Self::Identifier,
            T::StringLiteral => Self::StringLiteral,
            T::Number => Self::Number,
            T::Backslash => Self::Backslash,
            T::LeftBrace => Self::LeftBrace,
            T::RightBrace => Self::RightBrace,
            T::LeftBracket => Self::LeftBracket,
            T::RightBracket => Self::RightBracket,
            T::LeftParen => Self::LeftParen,
            T::RightParen => Self::RightParen,
            T::Dollar => Self::Dollar,
            T::DoubleDollar => Self::DoubleDollar,
            T::Ampersand => Self::Ampersand,
            T::Percent => Self::Percent,
            T::Hash => Self::Hash,
            T::Caret => Self::Caret,
            T::Underscore => Self::Underscore,
            T::Tilde => Self::Tilde,
            T::Equal => Self::Equal,
            T::Equals => Self::Equals,
            T::Plus => Self::Plus,
            T::Minus => Self::Minus,
            T::Star => Self::Star,
            T::Slash => Self::Slash,
            T::Pipe => Self::Pipe,
            T::Less => Self::Less,
            T::LessThan => Self::LessThan,
            T::Greater => Self::Greater,
            T::GreaterThan => Self::GreaterThan,
            T::Exclamation => Self::Exclamation,
            T::Question => Self::Question,
            T::At => Self::At,
            T::Colon => Self::Colon,
            T::Semicolon => Self::Semicolon,
            T::Comma => Self::Comma,
            T::Dot => Self::Dot,
            T::Comment => Self::Comment,
            T::Whitespace => Self::Whitespace,
            T::Newline => Self::Newline,
            T::BeginKeyword => Self::BeginKeyword,
            T::EndKeyword => Self::EndKeyword,
            T::DocumentclassKeyword => Self::DocumentclassKeyword,
            T::UsepackageKeyword => Self::UsepackageKeyword,
            T::SectionKeyword => Self::SectionKeyword,
            T::SubsectionKeyword => Self::SubsectionKeyword,
            T::SubsubsectionKeyword => Self::SubsubsectionKeyword,
            T::ChapterKeyword => Self::ChapterKeyword,
            T::PartKeyword => Self::PartKeyword,
            T::TitleKeyword => Self::TitleKeyword,
            T::AuthorKeyword => Self::AuthorKeyword,
            T::DateKeyword => Self::DateKeyword,
            T::MaketitleKeyword => Self::MaketitleKeyword,
            T::TableofcontentsKeyword => Self::TableofcontentsKeyword,
            T::ItemKeyword => Self::ItemKeyword,
            T::LabelKeyword => Self::LabelKeyword,
            T::RefKeyword => Self::RefKeyword,
            T::CiteKeyword => Self::CiteKeyword,
            T::IncludegraphicsKeyword => Self::IncludegraphicsKeyword,
            T::TextbfKeyword => Self::TextbfKeyword,
            T::TextitKeyword => Self::TextitKeyword,
            T::EmphKeyword => Self::EmphKeyword,
            T::Eof => Self::Eof,
        }
    }
}
